AYS-83 | Date Format Has Been Upgraded with Dynamic TimeZone and New Format
afet-yonetim-sistemi/ays-fe-institution pull request #199
Opened 2024-07-24 13:26 UTC by agitrubard

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [ ] Bug fix
- [X] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [X] **Summary:**
    - Add a short description (e.g., added or modified features).

- [X] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [X] **Local Testing:**
    - I have tested my changes locally on my browser, and they are working as expected.

- [X] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by ESLint.

- [X] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated.

- [X] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [X] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-07-24 13:56 UTC, NNakreSS requested changes

2024-07-24 13:56 UTC, NNakreSS commented on package.json
> +    "@types/luxon": "^3.4.2",
tip tanımlamaları gibi , sadece build aşamasında kullanılan paketler devDependencies olarak tanımlanmalı.

2024-07-24 16:44 UTC, agitrubard commented on package.json
> +    "@types/luxon": "^3.4.2",
Fixed ✅

2024-07-25 14:00 UTC, sanshigo345 approved these changes
lgtm

2024-07-25 16:13 UTC, NNakreSS approved these changes

2024-07-26 07:41 UTC, kevseroz approved these changes

2024-07-26 08:27 UTC, merged