AYS - 78 | Institution Registration Completion Page
afet-yonetim-sistemi/ays-fe-institution pull request #212
Opened 2024-08-12 13:16 UTC by Skaimarvas

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [ ] Bug fix
- [x] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [ ] **Summary:**
    - Add a short description (e.g., added or modified features).

- [ ] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on my browser, and they are working as expected.

- [ ] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by ESLint.

- [ ] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated.

- [ ] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

    - [ ] **Related Issue:**
    - Closes #AYS-345 (If there is a relevant issue)

- [ ] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-08-12 16:38 UTC, sanshigo345 requested changes

2024-08-12 16:38 UTC, sanshigo345 commented on package.json
>      "class-variance-authority": "^0.7.0",
dependency olarak neden böyle bir şey eklendi anlamadım

2024-08-12 16:38 UTC, sanshigo345 commented on src/api/controller/instutionController.ts
> +  http.post(`api/v1/admin-registration-application/${id}/complete`, form)
form için "any" hariç bir type versek daha iyi olur

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +    },
default valuelara ihtiyacımız var mı?

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +  const router = useRouter()
toogle/handle onsubmit gibi tanımlamalar birbirine yakın olursa daha iyi olur. burada state ve diğer router, t tanımlamaların içinde saklanmış 😄

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +
neden burada hardcoded bir value var? herkes bu value'yu kullanacaksa bunu başka bir yerde saklamalıyız

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +        } else {
response statusune bakmak yerine diğer sayfalardaki gibi then kullanabiliriz

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +      } finally {
console.log'u silebiliriz. mainde console.log bırakmak istemeyiz

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +      }
neden timeout var?

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +    // )
console.log ve commentlere ihtiyacımız yok, sanırım bu fonksiyona tümden ihtiyacımız yok?

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +
mssing dependecy

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +                            </SelectItem>
{' '} olmasa daha iyi olur

2024-08-12 16:38 UTC, sanshigo345 commented on src/app/(public)/register-completion/page.tsx
> +                            type="button"
diğer sayfalarda olduğu gibi shadcn buttonunu kullansak daha iyi olur

2024-08-12 16:38 UTC, sanshigo345 commented on src/components/phoneInput.tsx
bu dosyanın yeri diğer UI componentlarının bulunduğu src/components/ui olmalı

2024-08-12 16:38 UTC, sanshigo345 commented on src/modules/adminRegistrationApplications/constants/formSchema.ts
> -
bunlar diğer sayfalarda kullanılıyordu. silip yeniden kendi case'imize göre yazmak yerine 2 tarafa da uyacak şekilde ekleme yaparsak daha iyi olur

2024-08-12 16:38 UTC, sanshigo345 commented on src/modules/adminRegistrationApplications/service.ts
> +}
burada async'e olmazsa ve AxiosResponse type kullanılmaz ise daha iyi olur

2024-08-12 16:39 UTC, sanshigo345 commented
Main branchde çok fazla değişiklik var ve bu branchte yok gibi gözüküyor, ve merge conflictilerin de çözülmesi lazım.

2024-08-12 16:41 UTC, sanshigo345 commented
UI olara sayfa açıldığında component sayfanın üstüne yakınlaştırılsa iyi olur, description, title ile kurum adı label'ına arasında daha iyi konumlanabilir. şuan title'a çok yakın gözüküyor.

2024-08-19 13:18 UTC, kevseroz commented on src/modules/adminRegistrationApplications/service.ts
> +}
Interface'leri constants içine types dosyası oluşturup onun içinden çağıralım

2024-08-19 13:18 UTC, kevseroz commented on src/app/(public)/register-completion/page.tsx
> +  })
formSchema için ayrı bir dosya oluşturup oradan çağıralım. Örneği şuan mevcut main branch'ından incelenebilir.

2024-08-19 13:18 UTC, kevseroz commented on src/app/(public)/register-completion/page.tsx
> +        } else {
Evet, try catch yerine then catch yapısına geçirelim.

2024-08-19 13:18 UTC, kevseroz commented on src/app/(public)/register-completion/page.tsx
> +      {(loading && <LoadingSpinner />) || (
burada zaten loading varsa spinner gösterecek, or eklemek yerine ternary operator daha mantıklı geldi (?:)

2024-09-02 11:49 UTC, agitrubard commented
@Skaimarvas geliştirmeleirn bittiyse draft'tan çıkarabilir misin?

2024-09-15 12:28 UTC, sanshigo345 submitted a review, later dismissed

2024-09-15 12:38 UTC, sanshigo345 approved these changes

2024-09-15 12:39 UTC, merged