AYS-351 & AYS-352 | Preparation of forgot password screen & Preparing the Password Creation Screen
afet-yonetim-sistemi/ays-fe-institution pull request #217
Opened 2024-08-17 20:43 UTC by NNakreSS

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [ ] Bug fix
- [x] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [x] **Summary:**
    - Preparation of forgot password screen & Preparing the Password Creation Screen

- [x] **Title and Branch Naming Conventions:**
    - The pull request title follows the
      standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
    - The branch name follows one of the conventions outlined in
      the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**
    - I have tested my changes locally on my browser, and they are working as expected.

- [x] **Code Quality:**
    - The code is formatted according to the project's coding guidelines and style.
    - The code has been reviewed to ensure its quality.
    - The code does not contain any issues flagged by ESLint.

- [x] **Documentation:**
    - Necessary documentation has been added or existing documentation has been updated.

- [x] **Reviewers and Assignees:**
    - Default reviewers have been assigned to this pull request.
    - Assignees have been added if necessary.

- [x] **Related Issue:**
    - [AYS-351](https://afetyonetimsistemi.atlassian.net/browse/AYS-351) & [AYS-352](https://afetyonetimsistemi.atlassian.net/browse/AYS-352)

- [x] **Labels and Associations:**
    - No specific actions are required in the Labels and Associations section for this pull request.

2024-08-22 10:15 UTC, sanshigo345 requested changes

2024-08-22 10:15 UTC, sanshigo345 commented on src/components/password/ForgotPasswordModal.tsx
> +            />
input'a type ekleyebiliriz, bi de neden validator yok ben "e" yazıp request atabiliyorum atmasam daha iyi olabilir, standardd "@" var mı diye baksın filan

2024-08-23 07:32 UTC, kevseroz commented on src/components/password/ForgotPasswordModal.tsx
> +        variant: 'default'
Buraya success ekleyebilir miyiz? Yeni bir branch gönderdim, içinde success variantı da var, şuan mainde mevcut.

2024-09-15 14:02 UTC, sanshigo345 submitted a review, later dismissed

2024-09-15 14:26 UTC, sanshigo345 approved these changes

2024-09-15 14:26 UTC, merged