AYS-376 | Update fields in emergency evacuation applications page
afet-yonetim-sistemi/ays-fe-institution pull request #259
Opened 2024-12-13 17:43 UTC by murat-es

### Checklist

Before submitting your pull request, ensure the following:

- [ ] **Change Type:**
- [ ] Bug fix
- [x] Feature addition
- [ ] Documentation update
- [ ] Performance improvement
- [ ] Other (please specify)

- [ ] **Summary:**

  - Add a short description (e.g., added or modified features).

- [x] **Title and Branch Naming Conventions:**

  - The pull request title follows the
    standard: [Pull Request Naming Conventions](CONTRIBUTING.md#pull-request-naming-conventions).
  - The branch name follows one of the conventions outlined in
    the [Branch Naming Conventions](CONTRIBUTING.md#branch-naming-conventions).

- [x] **Local Testing:**

  - I have tested my changes locally on my browser, and they are working as expected.

- [x] **Code Quality:**

  - The code is formatted according to the project's coding guidelines and style.
  - The code has been reviewed to ensure its quality.
  - The code does not contain any issues flagged by ESLint.

- [ ] **Documentation:**

  - Necessary documentation has been added or existing documentation has been updated.

- [ ] **Reviewers and Assignees:**

  - Default reviewers have been assigned to this pull request.
  - Assignees have been added if necessary.

  - [ ] **Related Issue:**
  - Closes #AYS-345 (If there is a relevant issue)

- [x] **Labels and Associations:**
  - No specific actions are required in the Labels and Associations section for this pull request.

2024-12-14 10:28 UTC, sanshigo345 requested changes

2024-12-14 10:28 UTC, sanshigo345 commented on src/modules/emergencyEvacuationApplications/components/columns.tsx
> +        ),
tıpatıp aynı logic 3 kere art arda yazmaktansa, genel bir fonksiyon yazılıp o fonksiyon kullanılabilir

2024-12-14 10:28 UTC, sanshigo345 commented on src/modules/emergencyEvacuationApplications/components/columns.tsx
>    phoneNumber: PhoneNumber
mantıken bu alanların da zorunlu olmaması gerekmez mi

2024-12-14 16:59 UTC, murat-es commented on src/modules/emergencyEvacuationApplications/components/columns.tsx
>    phoneNumber: PhoneNumber
https://test-servis.afetyonetimsistemi.org/api/v1/emergency-evacuation-applications apisinden gelen veride bu alanlar her zaman dolu olarak geliyor. Benim interface'e eklediğim alanlar ise isInPerson alanı "true" olduğu zaman "null" olarak geliyor.

2024-12-14 17:03 UTC, sanshigo345 commented on src/modules/emergencyEvacuationApplications/components/columns.tsx
>    phoneNumber: PhoneNumber
buradaki type definition ile api arasında bi bağlantı var mı?

2024-12-23 11:38 UTC, sanshigo345 approved these changes

2024-12-23 11:38 UTC, merged